"""add next_class and time to courses

Revision ID: 17d891e459e3
Revises: 02cb4124ca28
Create Date: 2025-12-15 00:42:50.083081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d891e459e3'
down_revision: Union[str, Sequence[str], None] = '02cb4124ca28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('next_class', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'time')
    op.drop_column('courses', 'next_class')
    # ### end Alembic commands ###
