"""drop meeting_url from live_classes

Revision ID: 6196dcdcb0ce
Revises: 874753fa165a
Create Date: 2026-01-09 17:04:43.328529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6196dcdcb0ce'
down_revision: Union[str, Sequence[str], None] = '874753fa165a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_classes', 'meeting_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_classes', sa.Column('meeting_url', sa.String(), nullable=False))
    # ### end Alembic commands ###
