"""remove is_live from live_classes

Revision ID: 74eea57744e4
Revises: b968d6f329b2
Create Date: 2025-12-15 21:54:12.195535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74eea57744e4'
down_revision: Union[str, Sequence[str], None] = 'b968d6f329b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_classes_id'), table_name='live_classes')
    op.drop_table('live_classes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_classes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('starts_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ends_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('meeting_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_live', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('live_classes_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('live_classes_pkey'))
    )
    op.create_index(op.f('ix_live_classes_id'), 'live_classes', ['id'], unique=False)
    # ### end Alembic commands ###
